# Generated by Django 4.1.7 on 2023-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
